//
//  GlobalConstants.swift
//  MovieDB
//
//  Created by Samarth Paboowal on 27/03/19.
//  Copyright © 2019 Samarth Paboowal. All rights reserved.
//

import Foundation

struct GlobalConstants {
    
    static let MOVIE_CELL_REUSE_IDENTIFIER = "MOVIE_CELL_REUSE_IDENTIFIER"
    static let MOVIE_COVER_CELL_REUSE_IDENTIFIER = "MOVIE_COVER_CELL_REUSE_IDENTIFIER"
    static let MOVIE_SYNOPSIS_CELL_REUSE_IDENTIFIER = "MOVIE_SYNOPSIS_CELL_REUSE_IDENTIFIER"
    static let MOVIE_REVIEW_CELL_REUSE_IDENTIFIER = "MOVIE_REVIEW_CELL_REUSE_IDENTIFIER"
    static let MOVIE_CREDIT_CELL_REUSE_IDENTIFIER = "MOVIE_CREDIT_CELL_REUSE_IDENTIFIER"
    static let SIMILAR_MOVIE_CELL_REUSE_IDENTIFIER = "SIMILAR_MOVIE_CELL_REUSE_IDENTIFIER"
    static let REVIEW_COLLECTION_CELL_REUSE_IDENTIFIER = "REVIEW_COLLECTION_CELL_REUSE_IDENTIFIER"
    static let CREDIT_COLLECTION_CELL_REUSE_IDENTIFIER = "CREDIT_COLLECTION_CELL_REUSE_IDENTIFIER"
    static let SIMILAR_MOVIE_COLLECTION_CELL_REUSE_IDENTIFIER = "SIMILAR_MOVIE_COLLECTION_CELL_REUSE_IDENTIFIER"
}
